### ISSUE TITLE
Question on environments

### ISSUE THREAD

**Issue by Vasallius** [raineszm/obsidian-latex-environments#13]
I am trying some environments from: https://latex.wikia.org/wiki/List_of_LaTeX_environments#:~:text=The%20paragraph%20environments%20are%20center,quote%2C%20verbatim%2C%20and%20verse and I do not think this plugin supports all (such as enumerate environment)? As such, **what are the supported environments**?

**Comment by raineszm** [comment]
Interesting. The plugin should support any environment that doesn’t require options (I’m planning to add support for these too). 

Can you give me an example of a case where it isn’t working with the enumerate environment so I can see what’s going wrong?

**Comment by raineszm** [comment]
Taking a closer look, is your issue that enumerate environments don't render? If so, that isn't due to this plugin but is a limitation of MathJax, which Obsidian uses to render math.

This plugin does no rendering. It only provides some helpers for modifying surrounding environments in the markdown source.

 For a list of supported commands and environments in MathJax you can check [here](http://docs.mathjax.org/en/latest/input/tex/macros/#environments).

**Comment by raineszm** [comment]
Closing for lack of info but I'll be happy to take a second look if the issue remains.
